/* $Id: 9c5fa3f3ff60c09432366612e065935ad27449b4 $ */
#ifndef OUTPUTTYPE_INCLUDED
#define OUTPUTTYPE_INCLUDED

typedef enum {STD_OUTPUT, SAM_OUTPUT, M8_OUTPUT} Outputtype_T;

typedef enum {SIMPLE, SUMMARY, ALIGNMENT, CONTINUOUS, CONTINUOUS_BY_EXON,
	      EXONS_CDNA, EXONS_GENOMIC, EXONS_CDNA_WINTRONS, EXONS_GENOMIC_WINTRONS,
	      MASK_INTRONS, MASK_UTR_INTRONS, CDNA, PROTEIN_GENOMIC,
	      PSL_NT, PSL_PRO, GFF3_GENE, GFF3_MATCH_CDNA, GFF3_MATCH_EST, BEDPE,
	      SAM, COORDS, SPLICESITES, INTRONS, MAP_RANGES, MAP_EXONS} Printtype_T;

#endif
